server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3301/identity_service_project}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "g34ksPeEIg4sjPQN1tjahdHggcxX5IVytU0X/f/BUbe8plgGq5YR/HWGA303Wg0h"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
